In [27]:
import pandas as pd
import zipfile

import seaborn as sns

In [18]:
with zipfile.ZipFile('/content/microdados_censo_escolar_2021.zip') as z:
  print(*z.namelist(), sep='\n')

2021/
2021/Anexos/
2021/Anexos/ANEXO I - Dicionário de Dados/
2021/Anexos/ANEXO I - Dicionário de Dados/dicionário_dados_educaç╞o_básica.xlsx
2021/Anexos/ANEXO I - Dicionário de Dados/~$Dicionário de Dados da Educaç╞o Básica.xlsx
2021/Anexos/ANEXO II -  Questionários do Censo da Educaç╞o Basica/
2021/Anexos/ANEXO II -  Questionários do Censo da Educaç╞o Basica/Aluno.pdf
2021/Anexos/ANEXO II -  Questionários do Censo da Educaç╞o Basica/Escola.pdf
2021/Anexos/ANEXO II -  Questionários do Censo da Educaç╞o Basica/Gestor_Escolar.pdf
2021/Anexos/ANEXO II -  Questionários do Censo da Educaç╞o Basica/Profissional_Escolar.pdf
2021/Anexos/ANEXO II -  Questionários do Censo da Educaç╞o Basica/Turma.pdf
2021/dados/
2021/dados/md5_microdados_ed_basica_2021.txt
2021/dados/microdados_ed_basica_2021.csv
2021/leia-me/
2021/leia-me/Leia-me.pdf

In [19]:
with zipfile.ZipFile('/content/microdados_censo_escolar_2021.zip') as z:
  with z.open('2021/dados/microdados_ed_basica_2021.csv') as f:
    dados = pd.read_csv(f, encoding='latin-1', sep=';')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (27) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [20]:
dados.head()

,NU_ANO_CENSO,NO_REGIAO,CO_REGIAO,NO_UF,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,NO_MESORREGIAO,CO_MESORREGIAO,...,QT_TUR_FUND_AF,QT_TUR_MED,QT_TUR_PROF,QT_TUR_PROF_TEC,QT_TUR_EJA,QT_TUR_EJA_FUND,QT_TUR_EJA_MED,QT_TUR_ESP,QT_TUR_ESP_CC,QT_TUR_ESP_CE
0,2021,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,1102,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2021,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,1102,...,0.0,0.0,0.0,0.0,11.0,7.0,4.0,5.0,5.0,0.0
2,2021,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,1102,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2021,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,1102,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0
4,2021,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Leste Rondoniense,1102,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0

In [21]:
dados.columns.values

array(['NU_ANO_CENSO', 'NO_REGIAO', 'CO_REGIAO', 'NO_UF', 'SG_UF',
       'CO_UF', 'NO_MUNICIPIO', 'CO_MUNICIPIO', 'NO_MESORREGIAO',
       'CO_MESORREGIAO', 'NO_MICRORREGIAO', 'CO_MICRORREGIAO',
       'CO_DISTRITO', 'CO_ENTIDADE', 'NO_ENTIDADE', 'TP_DEPENDENCIA',
       'TP_CATEGORIA_ESCOLA_PRIVADA', 'TP_LOCALIZACAO',
       'TP_LOCALIZACAO_DIFERENCIADA', 'DS_ENDERECO', 'NU_ENDERECO',
       'DS_COMPLEMENTO', 'NO_BAIRRO', 'CO_CEP', 'NU_DDD', 'NU_TELEFONE',
       'TP_SITUACAO_FUNCIONAMENTO', 'CO_ORGAO_REGIONAL',
       'DT_ANO_LETIVO_INICIO', 'DT_ANO_LETIVO_TERMINO',
       'IN_VINCULO_SECRETARIA_EDUCACAO', 'IN_VINCULO_SEGURANCA_PUBLICA',
       'IN_VINCULO_SECRETARIA_SAUDE', 'IN_VINCULO_OUTRO_ORGAO',
       'IN_CONVENIADA_PP', 'TP_CONVENIO_PODER_PUBLICO',
       'IN_MANT_ESCOLA_PRIVADA_EMP', 'IN_MANT_ESCOLA_PRIVADA_ONG',
       'IN_MANT_ESCOLA_PRIVADA_OSCIP', 'IN_MANT_ESCOLA_PRIV_ONG_OSCIP',
       'IN_MANT_ESCOLA_PRIVADA_SIND', 'IN_MANT_ESCOLA_PRIVADA_SIST_S',
       'IN_MANT_ESCOLA_PRIVADA_S_FINS', 'NU_CNPJ_ESCOLA_PRIVADA',
       'NU_CNPJ_MANTENEDORA', 'TP_REGULAMENTACAO',
       'TP_RESPONSAVEL_REGULAMENTACAO', 'CO_ESCOLA_SEDE_VINCULADA',
       'CO_IES_OFERTANTE', 'IN_LOCAL_FUNC_PREDIO_ESCOLAR',
       'TP_OCUPACAO_PREDIO_ESCOLAR', 'IN_LOCAL_FUNC_SALAS_EMPRESA',
       'IN_LOCAL_FUNC_SOCIOEDUCATIVO', 'IN_LOCAL_FUNC_UNID_PRISIONAL',
       'IN_LOCAL_FUNC_PRISIONAL_SOCIO', 'IN_LOCAL_FUNC_TEMPLO_IGREJA',
       'IN_LOCAL_FUNC_CASA_PROFESSOR', 'IN_LOCAL_FUNC_GALPAO',
       'TP_OCUPACAO_GALPAO', 'IN_LOCAL_FUNC_SALAS_OUTRA_ESC',
       'IN_LOCAL_FUNC_OUTROS', 'IN_PREDIO_COMPARTILHADO',
       'IN_AGUA_FILTRADA', 'IN_AGUA_POTAVEL', 'IN_AGUA_REDE_PUBLICA',
       'IN_AGUA_POCO_ARTESIANO', 'IN_AGUA_CACIMBA', 'IN_AGUA_FONTE_RIO',
       'IN_AGUA_INEXISTENTE', 'IN_ENERGIA_REDE_PUBLICA',
       'IN_ENERGIA_GERADOR', 'IN_ENERGIA_GERADOR_FOSSIL',
       'IN_ENERGIA_OUTROS', 'IN_ENERGIA_RENOVAVEL',
       'IN_ENERGIA_INEXISTENTE', 'IN_ESGOTO_REDE_PUBLICA',
       'IN_ESGOTO_FOSSA_SEPTICA', 'IN_ESGOTO_FOSSA_COMUM',
       'IN_ESGOTO_FOSSA', 'IN_ESGOTO_INEXISTENTE',
       'IN_LIXO_SERVICO_COLETA', 'IN_LIXO_QUEIMA', 'IN_LIXO_ENTERRA',
       'IN_LIXO_DESTINO_FINAL_PUBLICO', 'IN_LIXO_DESCARTA_OUTRA_AREA',
       'IN_LIXO_JOGA_OUTRA_AREA', 'IN_LIXO_OUTROS', 'IN_LIXO_RECICLA',
       'IN_TRATAMENTO_LIXO_SEPARACAO', 'IN_TRATAMENTO_LIXO_REUTILIZA',
       'IN_TRATAMENTO_LIXO_RECICLAGEM', 'IN_TRATAMENTO_LIXO_INEXISTENTE',
       'IN_ALMOXARIFADO', 'IN_AREA_VERDE', 'IN_AUDITORIO',
       'IN_BANHEIRO_FORA_PREDIO', 'IN_BANHEIRO_DENTRO_PREDIO',
       'IN_BANHEIRO', 'IN_BANHEIRO_EI', 'IN_BANHEIRO_PNE',
       'IN_BANHEIRO_FUNCIONARIOS', 'IN_BANHEIRO_CHUVEIRO', 'IN_BERCARIO',
       'IN_BIBLIOTECA', 'IN_BIBLIOTECA_SALA_LEITURA', 'IN_COZINHA',
       'IN_DESPENSA', 'IN_DORMITORIO_ALUNO', 'IN_DORMITORIO_PROFESSOR',
       'IN_LABORATORIO_CIENCIAS', 'IN_LABORATORIO_INFORMATICA',
       'IN_PATIO_COBERTO', 'IN_PATIO_DESCOBERTO', 'IN_PARQUE_INFANTIL',
       'IN_PISCINA', 'IN_QUADRA_ESPORTES', 'IN_QUADRA_ESPORTES_COBERTA',
       'IN_QUADRA_ESPORTES_DESCOBERTA', 'IN_REFEITORIO',
       'IN_SALA_ATELIE_ARTES', 'IN_SALA_MUSICA_CORAL',
       'IN_SALA_ESTUDIO_DANCA', 'IN_SALA_MULTIUSO', 'IN_SALA_DIRETORIA',
       'IN_SALA_LEITURA', 'IN_SALA_PROFESSOR', 'IN_SALA_REPOUSO_ALUNO',
       'IN_SECRETARIA', 'IN_SALA_ATENDIMENTO_ESPECIAL', 'IN_TERREIRAO',
       'IN_VIVEIRO', 'IN_DEPENDENCIAS_PNE', 'IN_LAVANDERIA',
       'IN_DEPENDENCIAS_OUTRAS', 'IN_ACESSIBILIDADE_CORRIMAO',
       'IN_ACESSIBILIDADE_ELEVADOR', 'IN_ACESSIBILIDADE_PISOS_TATEIS',
       'IN_ACESSIBILIDADE_VAO_LIVRE', 'IN_ACESSIBILIDADE_RAMPAS',
       'IN_ACESSIBILIDADE_SINAL_SONORO', 'IN_ACESSIBILIDADE_SINAL_TATIL',
       'IN_ACESSIBILIDADE_SINAL_VISUAL', 'IN_ACESSIBILIDADE_INEXISTENTE',
       'QT_SALAS_EXISTENTES', 'QT_SALAS_UTILIZADAS_DENTRO',
       'QT_SALAS_UTILIZADAS_FORA', 'QT_SALAS_UTILIZADAS',
       'QT_SALAS_UTILIZA_CLIMATIZADAS', 'QT_SALAS_UTILIZADAS_ACESSIVEIS',
       'IN_EQUIP_PARABOLICA', 'IN_COMPUTADOR', 'IN_EQUIP_COPIADORA',
       'IN_EQUIP_IMPRESSORA', 'IN_EQUIP_IMPRESSORA_MULT',
       'IN_EQUIP_SCANNER', 'IN_EQUIP_NENHUM', 'IN_EQUIP_DVD',
       'QT_EQUIP_DVD', 'IN_EQUIP_SOM', 'QT_EQUIP_SOM', 'IN_EQUIP_TV',
       'QT_EQUIP_TV', 'IN_EQUIP_LOUSA_DIGITAL', 'QT_EQUIP_LOUSA_DIGITAL',
       'IN_EQUIP_MULTIMIDIA', 'QT_EQUIP_MULTIMIDIA',
       'IN_EQUIP_VIDEOCASSETE', 'IN_EQUIP_RETROPROJETOR', 'IN_EQUIP_FAX',
       'IN_EQUIP_FOTO', 'QT_EQUIP_VIDEOCASSETE', 'QT_EQUIP_PARABOLICA',
       'QT_EQUIP_COPIADORA', 'QT_EQUIP_RETROPROJETOR',
       'QT_EQUIP_IMPRESSORA', 'QT_EQUIP_IMPRESSORA_MULT', 'QT_EQUIP_FAX',
       'QT_EQUIP_FOTO', 'QT_COMP_ALUNO', 'IN_DESKTOP_ALUNO',
       'QT_DESKTOP_ALUNO', 'IN_COMP_PORTATIL_ALUNO',
       'QT_COMP_PORTATIL_ALUNO', 'IN_TABLET_ALUNO', 'QT_TABLET_ALUNO',
       'QT_COMPUTADOR', 'QT_COMP_ADMINISTRATIVO', 'IN_INTERNET',
       'IN_INTERNET_ALUNOS', 'IN_INTERNET_ADMINISTRATIVO',
       'IN_INTERNET_APRENDIZAGEM', 'IN_INTERNET_COMUNIDADE',
       'IN_ACESSO_INTERNET_COMPUTADOR', 'IN_ACES_INTERNET_DISP_PESSOAIS',
       'TP_REDE_LOCAL', 'IN_BANDA_LARGA', 'QT_FUNCIONARIOS',
       'IN_PROF_ADMINISTRATIVOS', 'QT_PROF_ADMINISTRATIVOS',
       'IN_PROF_SERVICOS_GERAIS', 'QT_PROF_SERVICOS_GERAIS',
       'IN_PROF_BIBLIOTECARIO', 'QT_PROF_BIBLIOTECARIO', 'IN_PROF_SAUDE',
       'QT_PROF_SAUDE', 'IN_PROF_COORDENADOR', 'QT_PROF_COORDENADOR',
       'IN_PROF_FONAUDIOLOGO', 'QT_PROF_FONAUDIOLOGO',
       'IN_PROF_NUTRICIONISTA', 'QT_PROF_NUTRICIONISTA',
       'IN_PROF_PSICOLOGO', 'QT_PROF_PSICOLOGO', 'IN_PROF_ALIMENTACAO',
       'QT_PROF_ALIMENTACAO', 'IN_PROF_PEDAGOGIA', 'QT_PROF_PEDAGOGIA',
       'IN_PROF_SECRETARIO', 'QT_PROF_SECRETARIO', 'IN_PROF_SEGURANCA',
       'QT_PROF_SEGURANCA', 'IN_PROF_MONITORES', 'QT_PROF_MONITORES',
       'IN_PROF_GESTAO', 'QT_PROF_GESTAO', 'IN_PROF_ASSIST_SOCIAL',
       'QT_PROF_ASSIST_SOCIAL', 'IN_ALIMENTACAO', 'IN_SERIE_ANO',
       'IN_PERIODOS_SEMESTRAIS', 'IN_FUNDAMENTAL_CICLOS',
       'IN_GRUPOS_NAO_SERIADOS', 'IN_MODULOS', 'IN_FORMACAO_ALTERNANCIA',
       'IN_MATERIAL_PED_MULTIMIDIA', 'IN_MATERIAL_PED_INFANTIL',
       'IN_MATERIAL_PED_CIENTIFICO', 'IN_MATERIAL_PED_DIFUSAO',
       'IN_MATERIAL_PED_MUSICAL', 'IN_MATERIAL_PED_JOGOS',
       'IN_MATERIAL_PED_ARTISTICAS', 'IN_MATERIAL_PED_DESPORTIVA',
       'IN_MATERIAL_PED_INDIGENA', 'IN_MATERIAL_PED_ETNICO',
       'IN_MATERIAL_PED_CAMPO', 'IN_MATERIAL_PED_NENHUM',
       'IN_MATERIAL_ESP_QUILOMBOLA', 'IN_MATERIAL_ESP_INDIGENA',
       'IN_MATERIAL_ESP_NAO_UTILIZA', 'IN_EDUCACAO_INDIGENA',
       'TP_INDIGENA_LINGUA', 'CO_LINGUA_INDIGENA_1',
       'CO_LINGUA_INDIGENA_2', 'CO_LINGUA_INDIGENA_3',
       'IN_BRASIL_ALFABETIZADO', 'IN_FINAL_SEMANA', 'IN_EXAME_SELECAO',
       'IN_RESERVA_PPI', 'IN_RESERVA_RENDA', 'IN_RESERVA_PUBLICA',
       'IN_RESERVA_PCD', 'IN_RESERVA_OUTROS', 'IN_RESERVA_NENHUMA',
       'IN_REDES_SOCIAIS', 'IN_ESPACO_ATIVIDADE', 'IN_ESPACO_EQUIPAMENTO',
       'IN_ORGAO_ASS_PAIS', 'IN_ORGAO_ASS_PAIS_MESTRES',
       'IN_ORGAO_CONSELHO_ESCOLAR', 'IN_ORGAO_GREMIO_ESTUDANTIL',
       'IN_ORGAO_OUTROS', 'IN_ORGAO_NENHUM', 'TP_PROPOSTA_PEDAGOGICA',
       'TP_AEE', 'TP_ATIVIDADE_COMPLEMENTAR', 'IN_MEDIACAO_PRESENCIAL',
       'IN_MEDIACAO_SEMIPRESENCIAL', 'IN_MEDIACAO_EAD', 'IN_REGULAR',
       'IN_DIURNO', 'IN_NOTURNO', 'IN_EAD', 'IN_BAS', 'IN_INF',
       'IN_INF_CRE', 'IN_INF_PRE', 'IN_FUND', 'IN_FUND_AI', 'IN_FUND_AF',
       'IN_MED', 'IN_PROF', 'IN_PROF_TEC', 'IN_EJA', 'IN_EJA_FUND',
       'IN_EJA_MED', 'IN_ESP', 'IN_ESP_CC', 'IN_ESP_CE', 'QT_MAT_BAS',
       'QT_MAT_INF', 'QT_MAT_INF_CRE', 'QT_MAT_INF_PRE', 'QT_MAT_FUND',
       'QT_MAT_FUND_AI', 'QT_MAT_FUND_AF', 'QT_MAT_MED', 'QT_MAT_PROF',
       'QT_MAT_PROF_TEC', 'QT_MAT_EJA', 'QT_MAT_EJA_FUND',
       'QT_MAT_EJA_MED', 'QT_MAT_ESP', 'QT_MAT_ESP_CC', 'QT_MAT_ESP_CE',
       'QT_MAT_BAS_FEM', 'QT_MAT_BAS_MASC', 'QT_MAT_BAS_ND',
       'QT_MAT_BAS_BRANCA', 'QT_MAT_BAS_PRETA', 'QT_MAT_BAS_PARDA',
       'QT_MAT_BAS_AMARELA', 'QT_MAT_BAS_INDIGENA', 'QT_MAT_BAS_0_3',
       'QT_MAT_BAS_4_5', 'QT_MAT_BAS_6_10', 'QT_MAT_BAS_11_14',
       'QT_MAT_BAS_15_17', 'QT_MAT_BAS_18_MAIS', 'QT_MAT_BAS_D',
       'QT_MAT_BAS_N', 'QT_MAT_BAS_EAD', 'QT_MAT_INF_INT',
       'QT_MAT_INF_CRE_INT', 'QT_MAT_INF_PRE_INT', 'QT_MAT_FUND_INT',
       'QT_MAT_FUND_AI_INT', 'QT_MAT_FUND_AF_INT', 'QT_MAT_MED_INT',
       'QT_DOC_BAS', 'QT_DOC_INF', 'QT_DOC_INF_CRE', 'QT_DOC_INF_PRE',
       'QT_DOC_FUND', 'QT_DOC_FUND_AI', 'QT_DOC_FUND_AF', 'QT_DOC_MED',
       'QT_DOC_PROF', 'QT_DOC_PROF_TEC', 'QT_DOC_EJA', 'QT_DOC_EJA_FUND',
       'QT_DOC_EJA_MED', 'QT_DOC_ESP', 'QT_DOC_ESP_CC', 'QT_DOC_ESP_CE',
       'QT_TUR_BAS', 'QT_TUR_INF', 'QT_TUR_INF_CRE', 'QT_TUR_INF_PRE',
       'QT_TUR_FUND', 'QT_TUR_FUND_AI', 'QT_TUR_FUND_AF', 'QT_TUR_MED',
       'QT_TUR_PROF', 'QT_TUR_PROF_TEC', 'QT_TUR_EJA', 'QT_TUR_EJA_FUND',
       'QT_TUR_EJA_MED', 'QT_TUR_ESP', 'QT_TUR_ESP_CC', 'QT_TUR_ESP_CE'],
      dtype=object)

In [22]:
dados.isnull().sum()

NU_ANO_CENSO           0
NO_REGIAO              0
CO_REGIAO              0
NO_UF                  0
SG_UF                  0
                   ...
QT_TUR_EJA_FUND    42770
QT_TUR_EJA_MED     42770
QT_TUR_ESP         42770
QT_TUR_ESP_CC      42770
QT_TUR_ESP_CE      42770
Length: 370, dtype: int64

In [23]:
dados.shape

(221140, 370)

In [24]:
dados.describe()

,NU_ANO_CENSO,CO_REGIAO,CO_UF,CO_MUNICIPIO,CO_MESORREGIAO,CO_MICRORREGIAO,CO_DISTRITO,CO_ENTIDADE,TP_DEPENDENCIA,TP_CATEGORIA_ESCOLA_PRIVADA,...,QT_TUR_FUND_AF,QT_TUR_MED,QT_TUR_PROF,QT_TUR_PROF_TEC,QT_TUR_EJA,QT_TUR_EJA_FUND,QT_TUR_EJA_MED,QT_TUR_ESP,QT_TUR_ESP_CC,QT_TUR_ESP_CE
count,221140.0,221140.000000,221140.000000,2.211400e+05,221140.000000,221140.000000,2.211400e+05,2.211400e+05,221140.000000,41254.000000,...,178370.000000,178370.000000,178370.000000,178370.000000,178370.000000,178370.000000,178370.000000,178370.000000,178370.000000,178370.000000
mean,2021.0,2.643244,30.179936,3.033187e+06,3023.000348,30199.700493,3.033187e+08,3.034655e+07,3.079140,1.647113,...,2.805741,1.445579,0.400768,0.385721,0.670657,0.449846,0.220811,4.199187,4.091282,0.107905
std,0.0,1.021892,9.464661,9.503146e+05,947.465563,9469.267232,9.503146e+07,9.467711e+06,0.629131,1.186024,...,4.785013,4.581926,3.335923,3.265061,3.375518,1.989178,2.075661,5.713421,5.632894,1.221506
min,2021.0,1.000000,11.000000,1.100015e+06,1101.000000,11001.000000,1.100015e+08,1.100002e+07,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2021.0,2.000000,23.000000,2.310605e+06,2305.000000,23023.000000,2.310605e+08,2.324940e+07,3.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2021.0,3.000000,31.000000,3.113305e+06,3103.000000,31014.000000,3.113305e+08,3.108646e+07,3.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,0.000000
75%,2021.0,3.000000,35.000000,3.547809e+06,3515.000000,35057.000000,3.547809e+08,3.524269e+07,3.000000,2.000000,...,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,6.000000,0.000000
max,2021.0,5.000000,53.000000,5.300108e+06,5301.000000,53001.000000,5.300108e+08,5.308803e+07,4.000000,4.000000,...,92.000000,164.000000,309.000000,309.000000,501.000000,181.000000,320.000000,101.000000,101.000000,81.000000

In [25]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221140 entries, 0 to 221139
Columns: 370 entries, NU_ANO_CENSO to QT_TUR_ESP_CE
dtypes: float64(344), int64(12), object(14)
memory usage: 624.3+ MB

In [29]:
dados['CO_UF'].value_counts()

35    33989
31    24023
29    20156
21    14162
33    13282
15    12395
43    11631
23    10654
26    10509
41    10079
42     7308
22     6645
13     6251
25     5638
24     5293
52     5152
32     4035
27     3435
51     3211
28     2547
17     2409
50     1889
12     1734
11     1431
53     1407
14      941
16      934
Name: CO_UF, dtype: int64

In [30]:
#olhando o dicionário, verifiquei a separação de algumas informações, como "cadastro da escola", onde agrupei

In [41]:
dados.loc[dados['SG_UF'] == 'MS']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

NU_ANO_CENSO       2.021000e+03
CO_REGIAO          5.000000e+00
CO_UF              5.000000e+01
CO_MUNICIPIO       5.004029e+06
CO_MESORREGIAO     5.002781e+03
                       ...
QT_TUR_EJA_FUND    3.503148e-01
QT_TUR_EJA_MED     1.608472e-01
QT_TUR_ESP         6.163709e+00
QT_TUR_ESP_CC      5.773326e+00
QT_TUR_ESP_CE      3.903835e-01
Length: 357, dtype: float64

In [44]:
dados.groupby(by=['NO_MUNICIPIO']).mean()

,NU_ANO_CENSO,CO_REGIAO,CO_UF,CO_MUNICIPIO,CO_MESORREGIAO,CO_MICRORREGIAO,CO_DISTRITO,CO_ENTIDADE,TP_DEPENDENCIA,TP_CATEGORIA_ESCOLA_PRIVADA,...,QT_TUR_FUND_AF,QT_TUR_MED,QT_TUR_PROF,QT_TUR_PROF_TEC,QT_TUR_EJA,QT_TUR_EJA_FUND,QT_TUR_EJA_MED,QT_TUR_ESP,QT_TUR_ESP_CC,QT_TUR_ESP_CE
NO_MUNICIPIO,,,,,,,,,,,,,,,,,,,,,
Abadia de Goiás,2021.0,5.0,52.0,5200050.0,5203.0,52010.0,5.200050e+08,5.209022e+07,3.000000,1.000000,...,3.333333,1.555556,0.000000,0.000000,0.333333,0.000000,0.333333,5.000000,5.000000,0.000000
Abadia dos Dourados,2021.0,3.0,31.0,3100104.0,3105.0,31019.0,3.100104e+08,3.124381e+07,3.000000,4.000000,...,2.000000,0.750000,0.000000,0.000000,0.125000,0.125000,0.000000,1.375000,1.125000,0.250000
Abadiânia,2021.0,5.0,52.0,5200100.0,5204.0,52012.0,5.200100e+08,5.207181e+07,3.083333,3.000000,...,3.083333,2.416667,0.000000,0.000000,0.583333,0.333333,0.250000,3.000000,3.000000,0.000000
Abaetetuba,2021.0,1.0,15.0,1500107.0,1504.0,15011.0,1.500107e+08,1.517568e+07,2.948357,1.538462,...,2.907317,1.380488,0.468293,0.468293,0.614634,0.370732,0.243902,4.502439,4.502439,0.000000
Abaeté,2021.0,3.0,31.0,3100203.0,3106.0,31024.0,3.100203e+08,3.116248e+07,3.125000,2.200000,...,2.450000,1.050000,0.100000,0.100000,0.600000,0.500000,0.100000,2.800000,2.600000,0.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Áurea,2021.0,4.0,43.0,4301552.0,4301.0,43004.0,4.301552e+08,4.304243e+07,2.666667,NaN,...,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.666667,1.666667,0.000000
Ângulo,2021.0,4.0,41.0,4101150.0,4103.0,41006.0,4.101150e+08,4.125384e+07,2.666667,NaN,...,2.666667,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,3.000000,0.000000
Érico Cardoso,2021.0,2.0,29.0,2900504.0,2906.0,29025.0,2.900504e+08,2.929612e+07,3.000000,1.000000,...,1.323529,0.264706,0.000000,0.000000,1.117647,1.058824,0.058824,1.058824,1.000000,0.058824
Óbidos,2021.0,1.0,15.0,1505106.0,1501.0,15001.0,1.505106e+08,1.514813e+07,2.990196,2.000000,...,3.326316,1.021053,0.231579,0.231579,0.357895,0.210526,0.147368,2.294737,2.294737,0.000000
Óleo,2021.0,3.0,35.0,3533809.0,3510.0,35040.0,3.533809e+08,3.521327e+07,2.800000,NaN,...,2.200000,0.600000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,0.000000