In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
dados = pd.read_excel('/content/INPC - Variação mensal, acumulada no ano e peso mensal, segundo o índice geral e os grupos de produt.xlsx')
dados.head()

,"INPC - Variação mensal, acumulada no ano e peso mensal, segundo o índice geral e os grupos de produtos e serviços",Unnamed: 1,Unnamed: 2,Unnamed: 3
0,Brasil - julho 2022,NaN,NaN,NaN
1,Índice geral e grupos de produtos e serviços,Variação mensal (%),Variação acumulada no ano (%),Peso mensal (%)
2,Índice geral,-0.6,4.98,100
3,Alimentação e bebidas,1.31,10.09,24.2459
4,Habitação,-0.83,-1.29,17.1103

In [ ]:
dados.shape

(13, 4)

In [ ]:
dados

,"INPC - Variação mensal, acumulada no ano e peso mensal, segundo o índice geral e os grupos de produtos e serviços",Unnamed: 1,Unnamed: 2,Unnamed: 3
0,Brasil - julho 2022,NaN,NaN,NaN
1,Índice geral e grupos de produtos e serviços,Variação mensal (%),Variação acumulada no ano (%),Peso mensal (%)
2,Índice geral,-0.6,4.98,100
3,Alimentação e bebidas,1.31,10.09,24.2459
4,Habitação,-0.83,-1.29,17.1103
5,Artigos de residência,0.2,7.44,4.7467
6,Vestuário,0.65,9.94,5.2519
7,Transportes,-4.44,2.22,21.0106
8,Saúde e cuidados pessoais,0.27,7.4,10.8671
9,Despesas pessoais,1.05,4.79,7.364
10,Educação,0.1,6.3,4.0815
11,Comunicação,0.07,2.08,5.3221
12,Fonte: IBGE - Índice Nacional de Preços ao Con...,NaN,NaN,NaN

In [ ]:
dados.rename(columns={
    'INPC - Variação mensal, acumulada no ano e peso mensal, segundo o índice geral e os grupos de produtos e serviços': 'Índice geral e grupos de produtos e serviços',
    'Unnamed: 1': 'Variação mensal (%)',
    'Unnamed: 2': 'Variação acumulada no ano (%)',
    'Unnamed: 3': 'Peso mensal (%)'
}, inplace=True)

In [ ]:
dados.drop(index=[0, 1], inplace=True)

In [ ]:
dados

,Índice geral e grupos de produtos e serviços,Variação mensal (%),Variação acumulada no ano (%),Peso mensal (%)
2,Índice geral,-0.6,4.98,100
3,Alimentação e bebidas,1.31,10.09,24.2459
4,Habitação,-0.83,-1.29,17.1103
5,Artigos de residência,0.2,7.44,4.7467
6,Vestuário,0.65,9.94,5.2519
7,Transportes,-4.44,2.22,21.0106
8,Saúde e cuidados pessoais,0.27,7.4,10.8671
9,Despesas pessoais,1.05,4.79,7.364
10,Educação,0.1,6.3,4.0815
11,Comunicação,0.07,2.08,5.3221
12,Fonte: IBGE - Índice Nacional de Preços ao Con...,NaN,NaN,NaN

In [ ]:
dados.drop(12, inplace=True)

In [ ]:
dados

,Índice geral e grupos de produtos e serviços,Variação mensal (%),Variação acumulada no ano (%),Peso mensal (%)
2,Índice geral,-0.6,4.98,100
3,Alimentação e bebidas,1.31,10.09,24.2459
4,Habitação,-0.83,-1.29,17.1103
5,Artigos de residência,0.2,7.44,4.7467
6,Vestuário,0.65,9.94,5.2519
7,Transportes,-4.44,2.22,21.0106
8,Saúde e cuidados pessoais,0.27,7.4,10.8671
9,Despesas pessoais,1.05,4.79,7.364
10,Educação,0.1,6.3,4.0815
11,Comunicação,0.07,2.08,5.3221